<a href="https://colab.research.google.com/github/sanjaneigory/IgorSanjane.github.io/blob/main/Credit_Card_Fraud_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Importing necessary libraries
import pandas as pd
import numpy as np

In [5]:
# Loading the dataset
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [6]:
# Visualize the first 5 rows
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [7]:
# This line give us the last 5 rows
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
65448,51589,-0.248790,1.080973,-0.917017,-0.976831,3.234594,2.963384,0.673578,0.509785,-0.674202,...,-0.160001,-0.482385,-0.326914,0.885378,0.220774,0.300600,-0.277872,-0.146796,0.76,0.0
65449,51589,1.130476,0.090195,0.358313,0.579876,-0.413699,-0.873547,0.192253,-0.105390,-0.005114,...,-0.438925,-1.421174,0.310895,0.353704,-0.083121,-0.015829,-0.046818,0.021914,42.90,0.0
65450,51590,1.298511,0.103767,0.026676,0.239810,0.066831,-0.021495,-0.125705,0.066416,-0.000780,...,-0.292495,-0.919318,-0.009714,-0.866837,0.313025,0.152421,-0.040222,-0.004856,1.98,0.0
65451,51591,-1.062891,0.242080,2.425183,1.125829,-1.284732,1.535764,-0.524604,1.074866,0.627453,...,0.194731,0.719323,0.072734,0.042001,0.060638,-0.254387,0.012123,0.010512,113.65,0.0
65452,51591,1.251499,0.352835,-0.173985,1.057454,0.345146,-0.366959,0.446715,-0.292922,-0.083856,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65453 entries, 0 to 65452
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    65453 non-null  int64
 1   V1      65453 non-null  float64
 2   V2      65453 non-null  float64
 3   V3      65453 non-null  float64
 4   V4      65453 non-null  float64
 5   V5      65453 non-null  float64
 6   V6      65453 non-null  float64
 7   V7      65453 non-null  float64
 8   V8      65453 non-null  float64
 9   V9      65453 non-null  float64
 10  V10     65453 non-null  float64
 11  V11     65452 non-null  float64
 12  V12     65452 non-null  float64
 13  V13     65452 non-null  float64
 14  V14     65452 non-null  float64
 15  V15     65452 non-null  float64
 16  V16     65452 non-null  float64
 17  V17     65452 non-null  float64
 18  V18     65452 non-null  float64
 19  V19     65452 non-null  float64
 20  V20     65452 non-null  float64
 21  V21     65452 non-null  float64
 22  V22     65452 non-null  float64
 23  V23     65452 non-null  float64
 24  V24     65452 non-null  float64
 25  V25     65452 non-null  float64
 26  V26     65452 non-null  float64
 27  V27     65452 non-null  float64
 28  V28     65452 non-null  float64
 29  Amount  65452 non-null  float64
 30  Class   65452 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 15.5 MB

In [11]:
# Checking the number of missing values on each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [14]:
# Check the distribution of legit transactions
credit_card_data['Class'].value_counts()

0.0    65283
1.0      169
Name: Class, dtype: int64

This data set is highly unbalanced, where:
0 --> Normal Transaction
1 --> Fraudulent Transaction

In [16]:
# Separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [17]:
print(legit.shape)
print(fraud.shape)

(65283, 31)
(169, 31)

In [18]:
# Statistical measures of the data
legit.Amount.describe()

count    65283.000000
mean        96.279722
std        270.360076
min          0.000000
25%          7.680000
50%         26.250000
75%         88.000000
max      19656.530000
Name: Amount, dtype: float64

In [19]:
fraud.Amount.describe()

count     169.000000
mean       94.895680
std       220.959331
min         0.000000
25%         1.000000
50%         7.610000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [20]:
# Compare the values for the two variables
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,33439.759478,-0.222825,-0.026270,0.710616,0.157998,-0.253909,0.109118,-0.094275,0.050530,0.045833,...,0.047148,-0.030787,-0.106567,-0.038539,0.005807,0.136450,0.019730,0.000695,0.004147,96.279722
1.0,29493.242604,-7.106029,5.115846,-9.566072,5.470948,-5.263861,-2.172211,-7.412550,3.501007,-3.298551,...,0.431494,0.850670,-0.212903,-0.255225,-0.075295,0.245601,0.107931,0.576249,0.041284,94.895680

In [ ]:
#Under-sampling

Build a sample dataset containing similar distribution of normal transactions and fraudulent transactions.

The number of fraudulent transactions is 169.

In [21]:
legit_sample = legit.sample(n=169)

Concatenating two data frames (Legit and Fraudulent)

In [22]:
new_dataset = pd.concat([legit_sample,fraud], axis=0)

In [24]:
# Will show legit transactions
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
63421,50706,-8.461845,6.866198,-11.838269,4.194211,-6.923097,-3.221147,-7.553497,6.015618,-2.466143,...,0.918244,-0.715366,0.210747,-0.060211,0.509535,-0.257284,1.170027,0.229301,99.99,1.0
63634,50808,-9.169790,7.092197,-12.354037,4.243069,-7.176438,-3.386618,-8.058012,6.442909,-2.412987,...,0.926157,-0.817706,-0.150434,-0.039383,0.485640,-0.264325,1.159690,0.232758,99.99,1.0
64329,51112,-9.848776,7.365546,-12.898538,4.273323,-7.611991,-3.427045,-8.350808,6.863604,-2.387567,...,0.931958,-0.874467,-0.192639,-0.035426,0.538665,-0.263934,1.134095,0.225973,99.99,1.0
64411,51135,-10.527304,7.639745,-13.443115,4.303403,-8.048210,-3.466997,-8.643193,7.284105,-2.362097,...,0.937416,-0.931178,-0.235697,-0.031393,0.591558,-0.263516,1.108897,0.219021,99.99,1.0
64460,51155,-11.205461,7.914633,-13.987752,4.333341,-8.484970,-3.506561,-8.935243,7.704449,-2.336584,...,0.942593,-0.987848,-0.279446,-0.027299,0.644344,-0.263078,1.084023,0.211933,99.99,1.0

In [25]:
# Will show fraudulent transactions
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
63421,50706,-8.461845,6.866198,-11.838269,4.194211,-6.923097,-3.221147,-7.553497,6.015618,-2.466143,...,0.918244,-0.715366,0.210747,-0.060211,0.509535,-0.257284,1.170027,0.229301,99.99,1.0
63634,50808,-9.169790,7.092197,-12.354037,4.243069,-7.176438,-3.386618,-8.058012,6.442909,-2.412987,...,0.926157,-0.817706,-0.150434,-0.039383,0.485640,-0.264325,1.159690,0.232758,99.99,1.0
64329,51112,-9.848776,7.365546,-12.898538,4.273323,-7.611991,-3.427045,-8.350808,6.863604,-2.387567,...,0.931958,-0.874467,-0.192639,-0.035426,0.538665,-0.263934,1.134095,0.225973,99.99,1.0
64411,51135,-10.527304,7.639745,-13.443115,4.303403,-8.048210,-3.466997,-8.643193,7.284105,-2.362097,...,0.937416,-0.931178,-0.235697,-0.031393,0.591558,-0.263516,1.108897,0.219021,99.99,1.0
64460,51155,-11.205461,7.914633,-13.987752,4.333341,-8.484970,-3.506561,-8.935243,7.704449,-2.336584,...,0.942593,-0.987848,-0.279446,-0.027299,0.644344,-0.263078,1.084023,0.211933,99.99,1.0

In [27]:
# Check the values counts
new_dataset['Class'].value_counts()

0.0    169
1.0    169
Name: Class, dtype: int64

As we can see it is aligned (balanced).

In [28]:
# Lets check the means
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,32000.804734,-0.167996,-0.048441,0.683603,0.103963,-0.219317,0.250030,-0.177293,-0.095936,0.071519,...,-0.055322,0.036435,-0.171310,-0.018384,0.026200,0.115624,0.041415,-0.034263,-0.020753,90.264556
1.0,29493.242604,-7.106029,5.115846,-9.566072,5.470948,-5.263861,-2.172211,-7.412550,3.501007,-3.298551,...,0.431494,0.850670,-0.212903,-0.255225,-0.075295,0.245601,0.107931,0.576249,0.041284,94.895680

(For Above) This tell us that the nature of the data has not changed (compared with the original dataset). So the difference is still here.

(For Below) Lets now split our data set into features and targets.

In [29]:
X = new_dataset.drop(columns = 'Class', axis=1) # 1 represents columns axis
Y = new_dataset['Class']

In [30]:
print(X)

        Time         V1        V2         V3        V4        V5        V6  \
60775  49498   0.353579 -1.914933  -0.272583  0.959399  0.775753  4.885873
22939  32510  -1.224646  1.486761   0.228262 -0.551697 -0.282495 -0.449590
36827  38701   1.063702 -0.022769   0.737689  1.169178 -0.566146 -0.053606
38026  39216  -0.890583  1.844070   1.635740  2.629907 -0.107527  0.025253
21490  31702  -0.840995 -0.065359   1.491384  0.579265  0.854627 -0.902110
...      ...        ...       ...        ...       ...       ...       ...
63421  50706  -8.461845  6.866198 -11.838269  4.194211 -6.923097 -3.221147
63634  50808  -9.169790  7.092197 -12.354037  4.243069 -7.176438 -3.386618
64329  51112  -9.848776  7.365546 -12.898538  4.273323 -7.611991 -3.427045
64411  51135 -10.527304  7.639745 -13.443115  4.303403 -8.048210 -3.466997
64460  51155 -11.205461  7.914633 -13.987752  4.333341 -8.484970 -3.506561

             V7        V8        V9  ...       V20       V21       V22  \
60775 -1.029248  1.204612  1.502868  ...  0.790582  0.106381 -0.273078
22939 -0.110859  0.927271 -0.635211  ... -0.312572  0.082073 -0.029065
36827 -0.366434  0.228899  0.110130  ... -0.195645  0.261105  0.689095
38026  0.360604  0.585085 -2.091876  ...  0.169534 -0.384647 -1.286296
21490 -0.059646  0.106692 -0.427737  ...  0.211864 -0.028771 -0.346228
...         ...       ...       ...  ...       ...       ...       ...
63421 -7.553497  6.015618 -2.466143  ...  0.814710  0.918244 -0.715366
63634 -8.058012  6.442909 -2.412987  ...  0.816652  0.926157 -0.817706
64329 -8.350808  6.863604 -2.387567  ...  0.832398  0.931958 -0.874467
64411 -8.643193  7.284105 -2.362097  ...  0.847085  0.937416 -0.931178
64460 -8.935243  7.704449 -2.336584  ...  0.860912  0.942593 -0.987848

            V23       V24       V25       V26       V27       V28  Amount
60775 -0.485221  1.063624  0.562340 -0.270685  0.031734  0.103138  420.00
22939  0.337214  0.000903 -1.297581 -0.255060 -0.069130  0.141105    2.69
36827 -0.089099  0.200472  0.434804 -0.219939  0.034548  0.017414   29.95
38026  0.065937  0.249210 -0.124431 -0.201405  0.178420  0.081433    7.99
21490  0.286877  0.052213 -0.811843  0.114691  0.113746  0.179326   10.22
...         ...       ...       ...       ...       ...       ...     ...
63421  0.210747 -0.060211  0.509535 -0.257284  1.170027  0.229301   99.99
63634 -0.150434 -0.039383  0.485640 -0.264325  1.159690  0.232758   99.99
64329 -0.192639 -0.035426  0.538665 -0.263934  1.134095  0.225973   99.99
64411 -0.235697 -0.031393  0.591558 -0.263516  1.108897  0.219021   99.99
64460 -0.279446 -0.027299  0.644344 -0.263078  1.084023  0.211933   99.99

[338 rows x 30 columns]

In [31]:
print(Y)

60775    0.0
22939    0.0
36827    0.0
38026    0.0
21490    0.0
        ...
63421    1.0
63634    1.0
64329    1.0
64411    1.0
64460    1.0
Name: Class, Length: 338, dtype: float64

Now we will split the data into training data and Testing data

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [37]:
print(X.shape, X_train.shape, X_test.shape)

(338, 30) (270, 30) (68, 30)

Model Training

Logistic Regression Model

In [46]:
model = LogisticRegression(solver='lbfgs', max_iter=500)

In [47]:
# training the Logistic Regression Model with training data
model.fit(X_train, Y_train)

LogisticRegression(max_iter=500)

Evaluate our model based on accuracy score

In [48]:
# Accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [49]:
print('Accuracy on training data: ', training_data_accuracy)

Accuracy on training data:  0.9592592592592593

In [52]:
# Accuracy on test data
X_test_prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [53]:
print('Accuracy on test data: ', testing_data_accuracy)

Accuracy on test data:  0.9558823529411765